package core;
import core.UserDefinedAction;
import core.controller.Core;
public class CustomAction extends UserDefinedAction {
    public void action(final Core controller) throws InterruptedException {
        /*Begin generated code*/
                controller.blockingWait(36);
                controller.mouse().move(507, 151);
                controller.blockingWait(8);
                controller.mouse().move(509, 152);
                controller.blockingWait(8);
                controller.mouse().move(511, 154);
                controller.blockingWait(8);
                controller.mouse().move(512, 155);
                controller.blockingWait(8);
                controller.mouse().move(515, 156);
                controller.blockingWait(8);
                controller.mouse().move(518, 157);
                controller.blockingWait(6);
                controller.mouse().move(520, 159);
                controller.blockingWait(8);
                controller.mouse().move(521, 159);
                controller.blockingWait(8);
                controller.mouse().move(522, 160);
                controller.blockingWait(8);
                controller.mouse().move(524, 161);
                controller.blockingWait(8);
                controller.mouse().move(525, 161);
                controller.blockingWait(8);
                controller.mouse().move(527, 162);
                controller.blockingWait(6);
                controller.mouse().move(528, 162);
                controller.blockingWait(8);
                controller.mouse().move(530, 163);
                controller.blockingWait(8);
                controller.mouse().move(533, 165);
                controller.blockingWait(8);
                controller.mouse().move(540, 169);
                controller.blockingWait(8);
                controller.mouse().move(546, 171);
                controller.blockingWait(6);
                controller.mouse().move(555, 175);
                controller.blockingWait(8);
                controller.mouse().move(566, 177);
                controller.blockingWait(8);
                controller.mouse().move(591, 184);
                controller.blockingWait(8);
                controller.mouse().move(605, 188);
                controller.blockingWait(8);
                controller.mouse().move(622, 193);
                controller.blockingWait(8);
                controller.mouse().move(638, 197);
                controller.blockingWait(8);
                controller.mouse().move(655, 200);
                controller.blockingWait(6);
                controller.mouse().move(689, 203);
                controller.blockingWait(8);
                controller.mouse().move(711, 205);
                controller.blockingWait(8);
                controller.mouse().move(730, 205);
                controller.blockingWait(8);
                controller.mouse().move(748, 205);
                controller.blockingWait(8);
                controller.mouse().move(769, 204);
                controller.blockingWait(6);
                controller.mouse().move(816, 198);
                controller.blockingWait(8);
                controller.mouse().move(837, 193);
                controller.blockingWait(8);
                controller.mouse().move(858, 186);
                controller.blockingWait(8);
                controller.mouse().move(874, 182);
                controller.blockingWait(8);
                controller.mouse().move(900, 172);
                controller.blockingWait(8);
                controller.mouse().move(909, 167);
                controller.blockingWait(6);
                controller.mouse().move(913, 163);
                controller.blockingWait(8);
                controller.mouse().move(918, 159);
                controller.blockingWait(8);
                controller.mouse().move(919, 156);
                controller.blockingWait(8);
                controller.mouse().move(919, 153);
                controller.blockingWait(8);
                controller.mouse().move(919, 150);
                controller.blockingWait(8);
                controller.mouse().move(919, 149);
                controller.blockingWait(6);
                controller.mouse().move(918, 147);
                controller.blockingWait(8);
                controller.mouse().move(915, 144);
                controller.blockingWait(8);
                controller.mouse().move(907, 140);
                controller.blockingWait(8);
                controller.mouse().move(900, 136);
                controller.blockingWait(8);
                controller.mouse().move(889, 132);
                controller.blockingWait(8);
                controller.mouse().move(875, 128);
                controller.blockingWait(6);
                controller.mouse().move(858, 124);
                controller.blockingWait(8);
                controller.mouse().move(821, 116);
                controller.blockingWait(8);
                controller.mouse().move(790, 111);
                controller.blockingWait(8);
                controller.mouse().move(755, 109);
                controller.blockingWait(8);
                controller.mouse().move(712, 107);
                controller.blockingWait(8);
                controller.mouse().move(633, 107);
                controller.blockingWait(6);
                controller.mouse().move(584, 107);
                controller.blockingWait(8);
                controller.mouse().move(536, 115);
                controller.blockingWait(8);
                controller.mouse().move(482, 124);
                controller.blockingWait(8);
                controller.mouse().move(431, 133);
                controller.blockingWait(8);
                controller.mouse().move(345, 158);
                controller.blockingWait(6);
                controller.mouse().move(303, 171);
                controller.blockingWait(8);
                controller.mouse().move(264, 186);
                controller.blockingWait(8);
                controller.mouse().move(227, 206);
                controller.blockingWait(8);
                controller.mouse().move(199, 221);
                controller.blockingWait(8);
                controller.mouse().move(163, 256);
                controller.blockingWait(8);
                controller.mouse().move(153, 270);
                controller.blockingWait(6);
                controller.mouse().move(147, 283);
                controller.blockingWait(8);
                controller.mouse().move(146, 295);
                controller.blockingWait(8);
                controller.mouse().move(146, 307);
                controller.blockingWait(8);
                controller.mouse().move(156, 328);
                controller.blockingWait(8);
                controller.mouse().move(166, 342);
                controller.blockingWait(8);
                controller.mouse().move(182, 356);
                controller.blockingWait(6);
                controller.mouse().move(200, 371);
                controller.blockingWait(8);
                controller.mouse().move(259, 407);
                controller.blockingWait(8);
                controller.mouse().move(299, 427);
                controller.blockingWait(8);
                controller.mouse().move(352, 449);
                controller.blockingWait(8);
                controller.mouse().move(411, 466);
                controller.blockingWait(8);
                controller.mouse().move(477, 483);
                controller.blockingWait(6);
                controller.mouse().move(600, 503);
                controller.blockingWait(8);
                controller.mouse().move(677, 511);
                controller.blockingWait(8);
                controller.mouse().move(761, 519);
                controller.blockingWait(8);
                controller.mouse().move(848, 522);
                controller.blockingWait(8);
                controller.mouse().move(938, 524);
                controller.blockingWait(8);
                controller.mouse().move(1084, 522);
                controller.blockingWait(6);
                controller.mouse().move(1164, 515);
                controller.blockingWait(8);
                controller.mouse().move(1235, 505);
                controller.blockingWait(8);
                controller.mouse().move(1294, 490);
                controller.blockingWait(8);
                controller.mouse().move(1332, 479);
                controller.blockingWait(8);
                controller.mouse().move(1360, 461);
                controller.blockingWait(8);
                controller.mouse().move(1365, 454);
                controller.blockingWait(6);
                controller.mouse().move(1365, 443);
                controller.blockingWait(8);
                controller.mouse().move(1365, 432);
                controller.blockingWait(8);
                controller.mouse().move(1365, 406);
                controller.blockingWait(8);
                controller.mouse().move(1365, 390);
                controller.blockingWait(8);
                controller.mouse().move(1363, 377);
                controller.blockingWait(8);
                controller.mouse().move(1362, 361);
                controller.blockingWait(6);
                controller.mouse().move(1359, 349);
                controller.blockingWait(8);
                controller.mouse().move(1351, 328);
                controller.blockingWait(8);
                controller.mouse().move(1346, 318);
                controller.blockingWait(8);
                controller.mouse().move(1340, 308);
                controller.blockingWait(8);
                controller.mouse().move(1331, 299);
                controller.blockingWait(6);
                controller.mouse().move(1318, 289);
                controller.blockingWait(8);
                controller.mouse().move(1283, 266);
                controller.blockingWait(8);
                controller.mouse().move(1251, 251);
                controller.blockingWait(8);
                controller.mouse().move(1211, 234);
                controller.blockingWait(8);
                controller.mouse().move(1164, 215);
                controller.blockingWait(8);
                controller.mouse().move(1112, 198);
                controller.blockingWait(6);
                controller.mouse().move(1016, 176);
                controller.blockingWait(8);
                controller.mouse().move(962, 169);
                controller.blockingWait(8);
                controller.mouse().move(910, 167);
                controller.blockingWait(8);
                controller.mouse().move(858, 167);
                controller.blockingWait(8);
                controller.mouse().move(769, 180);
                controller.blockingWait(8);
                controller.mouse().move(721, 191);
                controller.blockingWait(6);
                controller.mouse().move(678, 209);
                controller.blockingWait(8);
                controller.mouse().move(641, 231);
                controller.blockingWait(8);
                controller.mouse().move(605, 258);
                controller.blockingWait(8);
                controller.mouse().move(551, 309);
                controller.blockingWait(8);
                controller.mouse().move(531, 337);
                controller.blockingWait(8);
                controller.mouse().move(515, 368);
                controller.blockingWait(6);
                controller.mouse().move(506, 393);
                controller.blockingWait(8);
                controller.mouse().move(503, 416);
                controller.blockingWait(8);
                controller.mouse().move(508, 459);
                controller.blockingWait(8);
                controller.mouse().move(518, 479);
                controller.blockingWait(8);
                controller.mouse().move(533, 498);
                controller.blockingWait(8);
                controller.mouse().move(554, 520);
                controller.blockingWait(6);
                controller.mouse().move(583, 543);
                controller.blockingWait(8);
                controller.mouse().move(654, 580);
                controller.blockingWait(8);
                controller.mouse().move(700, 594);
                controller.blockingWait(8);
                controller.mouse().move(751, 605);
                controller.blockingWait(8);
                controller.mouse().move(808, 612);
                controller.blockingWait(8);
                controller.mouse().move(908, 612);
                controller.blockingWait(6);
                controller.mouse().move(964, 611);
                controller.blockingWait(8);
                controller.mouse().move(1022, 599);
                controller.blockingWait(8);
                controller.mouse().move(1078, 582);
                controller.blockingWait(8);
                controller.mouse().move(1128, 563);
                controller.blockingWait(8);
                controller.mouse().move(1209, 519);
                controller.blockingWait(8);
                controller.mouse().move(1244, 495);
                controller.blockingWait(6);
                controller.mouse().move(1266, 477);
                controller.blockingWait(8);
                controller.mouse().move(1278, 466);
                controller.blockingWait(8);
                controller.mouse().move(1283, 453);
                controller.blockingWait(8);
                controller.mouse().move(1283, 436);
                controller.blockingWait(8);
                controller.mouse().move(1279, 424);
                controller.blockingWait(8);
                controller.mouse().move(1269, 411);
                controller.blockingWait(6);
                controller.mouse().move(1255, 396);
                controller.blockingWait(8);
                controller.mouse().move(1236, 378);
                controller.blockingWait(8);
                controller.mouse().move(1187, 342);
                controller.blockingWait(8);
                controller.mouse().move(1155, 318);
                controller.blockingWait(8);
                controller.mouse().move(1114, 293);
                controller.blockingWait(8);
                controller.mouse().move(1067, 269);
                controller.blockingWait(6);
                controller.mouse().move(972, 228);
                controller.blockingWait(8);
                controller.mouse().move(911, 200);
                controller.blockingWait(8);
                controller.mouse().move(848, 177);
                controller.blockingWait(8);
                controller.mouse().move(785, 154);
                controller.blockingWait(8);
                controller.mouse().move(723, 137);
                controller.blockingWait(8);
                controller.mouse().move(838, 117);
                controller.blockingWait(0);
                controller.mouse().move(624, 118);
                controller.blockingWait(5);
                controller.mouse().press(1024);
                controller.blockingWait(1);
                controller.mouse().move(578, 116);
                controller.blockingWait(8);
                controller.mouse().move(532, 117);
                controller.blockingWait(8);
                controller.mouse().move(491, 125);
                controller.blockingWait(8);
                controller.mouse().move(462, 139);
                controller.blockingWait(8);
                controller.mouse().move(419, 170);
                controller.blockingWait(6);
                controller.mouse().move(405, 185);
                controller.blockingWait(8);
                controller.mouse().move(398, 201);
                controller.blockingWait(8);
                controller.mouse().move(395, 217);
                controller.blockingWait(8);
                controller.mouse().move(395, 230);
                controller.blockingWait(8);
                controller.mouse().move(404, 251);
                controller.blockingWait(8);
                controller.mouse().move(415, 262);
                controller.blockingWait(6);
                controller.mouse().move(428, 275);
                controller.blockingWait(8);
                controller.mouse().move(448, 290);
                controller.blockingWait(8);
                controller.mouse().move(499, 322);
                controller.blockingWait(8);
                controller.mouse().move(533, 339);
                controller.blockingWait(8);
                controller.mouse().move(573, 357);
                controller.blockingWait(2);
                controller.mouse().move(838, 117);
                controller.blockingWait(5);
                controller.mouse().release(1024);
                controller.blockingWait(1);
                controller.mouse().move(615, 372);
                controller.blockingWait(6);
                controller.mouse().move(661, 388);
                controller.blockingWait(8);
                controller.mouse().move(744, 410);
                controller.blockingWait(8);
                controller.mouse().move(788, 418);
                controller.blockingWait(8);
                controller.mouse().move(831, 423);
                controller.blockingWait(8);
                controller.mouse().move(871, 427);
                controller.blockingWait(8);
                controller.mouse().move(909, 427);
                controller.blockingWait(6);
                controller.mouse().move(975, 425);
                controller.blockingWait(8);
                controller.mouse().move(1009, 419);
                controller.blockingWait(8);
                controller.mouse().move(1037, 410);
                controller.blockingWait(8);
                controller.mouse().move(1063, 399);
                controller.blockingWait(8);
                controller.mouse().move(1080, 388);
                controller.blockingWait(9);
                controller.mouse().move(1106, 366);
                controller.blockingWait(6);
                controller.mouse().move(1113, 355);
                controller.blockingWait(8);
                controller.mouse().move(1117, 344);
                controller.blockingWait(8);
                controller.mouse().move(1117, 334);
                controller.blockingWait(8);
                controller.mouse().move(1117, 315);
                controller.blockingWait(8);
                controller.mouse().move(1111, 303);
                controller.blockingWait(8);
                controller.mouse().move(1104, 290);
                controller.blockingWait(6);
                controller.mouse().move(1094, 278);
                controller.blockingWait(8);
                controller.mouse().move(1082, 263);
                controller.blockingWait(8);
                controller.mouse().move(1045, 226);
                controller.blockingWait(8);
                controller.mouse().move(1023, 207);
                controller.blockingWait(8);
                controller.mouse().move(998, 188);
                controller.blockingWait(8);
                controller.mouse().move(967, 167);
                controller.blockingWait(6);
                controller.mouse().move(936, 151);
                controller.blockingWait(8);
                controller.mouse().move(875, 120);
                controller.blockingWait(8);
                controller.mouse().move(843, 106);
                controller.blockingWait(8);
                controller.mouse().move(811, 96);
                controller.blockingWait(8);
                controller.mouse().move(783, 89);
                controller.blockingWait(8);
                controller.mouse().move(760, 85);
                controller.blockingWait(6);
                controller.mouse().move(725, 83);
                controller.blockingWait(8);
                controller.mouse().move(711, 84);
                controller.blockingWait(8);
                controller.mouse().move(698, 89);
                controller.blockingWait(8);
                controller.mouse().move(687, 96);
                controller.blockingWait(8);
                controller.mouse().move(678, 106);
                controller.blockingWait(6);
                controller.mouse().move(665, 125);
                controller.blockingWait(8);
                controller.mouse().move(659, 136);
                controller.blockingWait(8);
                controller.mouse().move(655, 148);
                controller.blockingWait(3);
                controller.mouse().move(716, 113);
                controller.blockingWait(5);
                controller.mouse().press(1024);
                controller.blockingWait(0);
                controller.mouse().move(654, 161);
                controller.blockingWait(8);
                controller.mouse().move(654, 179);
                controller.blockingWait(8);
                controller.mouse().move(658, 190);
                controller.blockingWait(6);
                controller.mouse().move(664, 201);
                controller.blockingWait(8);
                controller.mouse().move(671, 212);
                controller.blockingWait(8);
                controller.mouse().move(679, 223);
                controller.blockingWait(8);
                controller.mouse().move(702, 242);
                controller.blockingWait(8);
                controller.mouse().move(713, 252);
                controller.blockingWait(8);
                controller.mouse().move(727, 261);
                controller.blockingWait(6);
                controller.mouse().move(745, 268);
                controller.blockingWait(8);
                controller.mouse().move(761, 274);
                controller.blockingWait(8);
                controller.mouse().move(796, 281);
                controller.blockingWait(8);
                controller.mouse().move(813, 283);
                controller.blockingWait(1);
                controller.mouse().move(716, 113);
                controller.blockingWait(5);
                controller.mouse().release(1024);
                controller.blockingWait(2);
                controller.mouse().move(830, 283);
                controller.blockingWait(8);
                controller.mouse().move(845, 283);
                controller.blockingWait(6);
                controller.mouse().move(859, 283);
                controller.blockingWait(8);
                controller.mouse().move(883, 280);
                controller.blockingWait(8);
                controller.mouse().move(895, 276);
                controller.blockingWait(8);
                controller.mouse().move(905, 272);
                controller.blockingWait(8);
                controller.mouse().move(914, 266);
                controller.blockingWait(8);
                controller.mouse().move(925, 257);
                controller.blockingWait(6);
                controller.mouse().move(930, 250);
                controller.blockingWait(8);
                controller.mouse().move(934, 244);
                controller.blockingWait(8);
                controller.mouse().move(935, 236);
                controller.blockingWait(8);
                controller.mouse().move(936, 229);
                controller.blockingWait(8);
                controller.mouse().move(936, 219);
                controller.blockingWait(8);
                controller.mouse().move(935, 213);
                controller.blockingWait(6);
                controller.mouse().move(931, 206);
                controller.blockingWait(8);
                controller.mouse().move(926, 199);
                controller.blockingWait(8);
                controller.mouse().move(920, 193);
                controller.blockingWait(8);
                controller.mouse().move(903, 181);
                controller.blockingWait(8);
                controller.mouse().move(892, 175);
                controller.blockingWait(8);
                controller.mouse().move(881, 168);
                controller.blockingWait(6);
                controller.mouse().move(869, 164);
                controller.blockingWait(8);
                controller.mouse().move(856, 159);
                controller.blockingWait(8);
                controller.mouse().move(836, 154);
                controller.blockingWait(8);
                controller.mouse().move(826, 152);
                controller.blockingWait(8);
                controller.mouse().move(817, 152);
                controller.blockingWait(8);
                controller.mouse().move(810, 152);
                controller.blockingWait(6);
                controller.mouse().move(800, 152);
                controller.blockingWait(8);
                controller.mouse().move(796, 153);
                controller.blockingWait(8);
                controller.mouse().move(793, 155);
                controller.blockingWait(8);
                controller.mouse().move(791, 156);
                controller.blockingWait(8);
                controller.mouse().move(790, 157);
                controller.blockingWait(1);
                controller.mouse().move(796, 109);
                controller.blockingWait(5);
                controller.mouse().press(1024);
                controller.blockingWait(0);
                controller.mouse().move(789, 160);
                controller.blockingWait(8);
                controller.mouse().move(788, 160);
                controller.blockingWait(8);
                controller.mouse().move(788, 161);
                controller.blockingWait(8);
                controller.mouse().move(787, 162);
                controller.blockingWait(77);
                controller.mouse().move(796, 109);
                controller.blockingWait(5);
                controller.mouse().release(1024);
                controller.blockingWait(233);
                controller.mouse().move(653, 141);
                controller.blockingWait(5);
                controller.mouse().press(1024);
                controller.blockingWait(95);
                controller.mouse().move(653, 141);
                controller.blockingWait(5);
                controller.mouse().release(1024);
                controller.blockingWait(239);
                controller.mouse().move(727, 81);
                controller.blockingWait(5);
                controller.mouse().press(1024);
                controller.blockingWait(87);
                controller.mouse().move(727, 81);
                controller.blockingWait(5);
                controller.mouse().release(1024);
                controller.blockingWait(739);
                controller.mouse().move(67, 69);
                controller.blockingWait(5);
    }
}