<#macro fragment>
     <!--   Core JS Files   -->
    <script src="/static/js/jquery.3.2.1.min.js" type="text/javascript"></script>
    <script src="/static/js/bootstrap.min.js" type="text/javascript"></script>

    <!--  Notifications Plugin    -->
    <script src="/static/js/bootstrap-notify.js"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
    <script src="/static/js/light-bootstrap-dashboard.js?v=1.4.0"></script>
</#macro>